FROM gcr.io/distroless/cc:debug

ARG MODULE_NAME="dt-main"
ARG APE_DTS_IMAGE_TAG=""
ARG APE_DTS_COMMIT_ID=""
ARG TARGETOS 
ARG TARGETARCH

ENV APE_DTS_IMAGE_TAG=${APE_DTS_IMAGE_TAG}
ENV APE_DTS_COMMIT_ID=${APE_DTS_COMMIT_ID}

COPY --chmod=777 ${TARGETARCH}-unknown-${TARGETOS}-gnu-${MODULE_NAME} /ape-dts
COPY log4rs.yaml /log4rs.yaml

ENTRYPOINT [ "/ape-dts" ]
